export const job = [
  {
    id: 1,
    title: "Associate Platform Consultant",
    location: "Karachi",
    description:
      "Abdullah LTD is a leading provider of innovative technology solutions and services, dedicated to helping businesses transform and succeed in the digital age. We are committed to delivering exceptional customer experiences and driving operational excellence We are seeking a motivated and detail-oriented Associate Platform Consultant to join our dynamic team. In this role, you will support the implementation and optimization of our platform solutions for clients. You will work closely with senior consultants, project managers, and clients to ensure the successful deployment and adoption of our technologies.",
    responsibilities: [
      "Bill Payment",
      "Incident management",
      "ATM key Management",
      "Bill Payment",
      "Incident management",
      "ATM key Management",
      "Bill Payment",
      "Incident management",
      "ATM key Management",
    ],
    qulifications: [
      "Designation Application consultant(Desired Education BS)",
      "Reposts to Manager",
      "Designation Application consultant",
      "Desired Education BS",
      "Reposts to Manager",
      "Experience: 3-5 years",
    ],
  },
  {
    id: 2,
    title: "Associate Platform Consultant",
    location: "Hyderabad",
    description:
      "Abdullah LTD is a leading provider of innovative technology solutions and services, dedicated to helping businesses transform and succeed in the digital age. We are committed to delivering exceptional customer experiences and driving operational excellence We are seeking a motivated and detail-oriented Associate Platform Consultant to join our dynamic team. In this role, you will support the implementation and optimization of our platform solutions for clients. You will work closely with senior consultants, project managers, and clients to ensure the successful deployment and adoption of our technologies.",
    responsibilities: [
      "Bill Payment",
      "Incident management",
      "ATM key Management",
      "Bill Payment",
      "Incident management",
      "ATM key Management",
      "Bill Payment",
      "Incident management",
      "ATM key Management",
    ],
    qulifications: [
      "Designation Application consultant(Desired Education BS)",
      "Reposts to Manager",
      "Designation Application consultant",
      "Desired Education BS",
      "Reposts to Manager",
      "Experience: 3-5 years",
    ],
  },
  {
    id: 3,
    title: "Associate Platform Consultant",
    location: "Lahore",
    description:
      "Abdullah LTD is a leading provider of innovative technology solutions and services, dedicated to helping businesses transform and succeed in the digital age. We are committed to delivering exceptional customer experiences and driving operational excellence We are seeking a motivated and detail-oriented Associate Platform Consultant to join our dynamic team. In this role, you will support the implementation and optimization of our platform solutions for clients. You will work closely with senior consultants, project managers, and clients to ensure the successful deployment and adoption of our technologies.",
    responsibilities: [
      "Bill Payment",
      "Incident management",
      "ATM key Management",
      "Bill Payment",
      "Incident management",
      "ATM key Management",
      "Bill Payment",
      "Incident management",
      "ATM key Management",
    ],
    qulifications: [
      "Designation Application consultant(Desired Education BS)",
      "Reposts to Manager",
      "Designation Application consultant",
      "Desired Education BS",
      "Reposts to Manager",
      "Experience: 3-5 years",
    ],
  },
];

export const question = [
  {
    Qno1: "1",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "2",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "3",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "4",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "5",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "6",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "7",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "8",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "9",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "10",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
  {
    Qno1: "12",
    Q: " Which of the following is not a pillar of OOP?",
    A: " Encapsulation",
    B: "Inheritance",
    C: " Polymorphism",
    D: "Compilation",
    correct: "Compilation",
  },
];

export const dataId = [
  {
    no1: "Name",
    title: "Amaar Raza",
  },
  {
    no1: "Email",
    title: "razaammar582@gmail.com",
  },
  {
    no1: "Contact",
    title: "+92304-3042589",
  },
  {
    no1: "Higher Education",
    title: "Be. Software Engineering",
  },
  {
    no1: "Work Exprience",
    title: "5 years",
  },
  {
    no1: "Gender",
    title: "Male",
  },
  {
    no1: "Shift",
    title: "Day or Night",
  },
  {
    no1: "Higher Education",
    title: "Be. Software Engineering",
  },
];
